
server:
  port: 9900
spring:
  application:
    name: shard-jdbc-starter
mybatis:
  mapper-locations: classpath:mapper/base/*.xml
  type-aliases-package: com.sun.shard.bean


sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.84.226.22:3306/sharding
        username: root
        password: chanbuy888
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/order2
#        username: root
#        password: root
    config:
      sharding:
        props:
          sql.show: true
        tables:
          order:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.order${0..1}  #数据节点
#            database-strategy:  #分库策略
#              inline:
#                sharding-column: city_id
#                algorithm-expression: ds${city_id % 2}
            table-strategy:  #分表策略
              inline:
                shardingColumn: id
                algorithm-expression: order${id % 2}
#          t_address:
#            key-generator-column-name: id
#            actual-data-nodes: ds${0..1}.t_address
#            database-strategy:
#              inline:
#                shardingColumn: lit
#                algorithm-expression: ds${lit % 2}